server:
  port: 8080
  servlet:
    context-path: /springboot
    application-display-name: 学习Spring Boot+MyBatis的例子
    
spring: 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  messages:
    encoding: utf-8
    basename: i18n/message-resources
    
  security:
    user:
      name: admin
      password: 111111
      roles:
      - ADMIN
      - USER
                   
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      
  datasource:
    name: dsMaster
    url: jdbc:mysql://127.0.0.1:3306/sxstu?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 12345666
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## 使用Hikar数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-boot
      auto-commit: true
      ## 连接池能达到的最大规模(包含空闲连接的数量和使用中的连接数量)
      maximum-pool-size: 10
      ## 连接池中的最小空闲连接数
      minimum-idle: 1
      ## 测试连接的sql语句
      connection-test-query: select 1
      ## 登陆数据库超时秒数
      login-timeout: 5
      ## 建立连接时超时毫秒数(30秒)
      connection-timeout: 30000
      ## 验证超时毫秒数(5秒)
      validation-timeout: 5000
      ## 连接能保持空闲的最长毫秒数(10分钟)
      idle-timeout: 600000
      ## 连接最长存活毫秒数(30分钟)
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  ## 实体包(可选)
  type-aliases-package: org.teach.study.boot.entity
  configuration:
    call-setters-on-nulls: true
    auto-mapping-behavior: full
   
pagehelper:
  auto-dialect: true  
  
rock:
  idgen:
    table: seqgen
    initial: 1000
    cache: 50
    key-field-name: f_seqname
    value-field-name: f_seqvalue
    
encoder:
  crypt:
    enable: false
    use-captcha: false
    
#logging:
#  config: classpath:logback.xml
  