server:
 port: 8080
 servlet:
    context-path: /springboot
    application-display-name: 学习springboot

spring: 
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher          
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

        
        
  datasource:
   name: dsMaster
   url: jdbc:mysql://localhost:3306/sxstu?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
   username: root
   password: 12345666
   driver-class-name: com.mysql.cj.jdbc.Driver
   ## 使用Hikar数据源
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      pool-name: hikari-study-boot
      auto-commit: false
      ## 连接池能达到的最大规模(包含空闲连接的数量和使用中的连接数量)
      maximum-pool-size: 10
      ## 连接池中的最小空闲连接数
      minimum-idle: 1
      ## 测试连接的sql语句
      connection-test-query: select 1
      ## 登陆数据库超时秒数
      login-timeout: 5
      ## 建立连接时超时毫秒数(30秒)
      connection-timeout: 30000
      ## 验证超时毫秒数(5秒)
      validation-timeout: 5000
      ## 连接能保持空闲的最长毫秒数(10分钟)
      idle-timeout: 600000
      ## 连接最长存活毫秒数(30分钟)
      max-lifetime: 1800000 
      
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  ## 实体包(可选)
  type-aliases-package: org.stu.boot1.entity
  configuration:
    call-setters-on-nulls: true
         
logging:
  config: classpath:logback.xml  
      